try:
     #statements which could generate 
     #exception
except:
     #Soloution of generated exception



or


try:
     #statements which could generate 
     #exception
except:
     #Soloution of generated exception
finally:
    print("I am always executed")]





ex:

try:
    num = int(input("Enter an integer: "))
except ValueError:
    print("Number entered is not an integer.")



ex:

try:
    num = int(input("Enter an integer: "))
    a = [6, 3]
    print(a[num])
except ValueError:
    print("Number entered is not an integer.")
    
except IndexError:
  print("Index Error")




ex:
def func1():
  try:
    l = [1, 5, 6, 7]
    i = int(input("Enter the index: "))
    print(l[i])
    return 1
  except:
    print("Some error occurred")
    return 0
  finally:
    print("I am always executed")
  # print("I am always executed")


x = func1()
print(x)